# Generated by Django 4.1.6 on 2023-02-15 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persons',
            name='joindate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='persons',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
